<?php
namespace gamboamartin\boletaje\models;
use base\orm\modelo;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class bol_invitacion extends modelo{
    public function __construct(PDO $link){
        $tabla = 'bol_invitacion';
        $columnas = array($tabla=>false);
        $campos_obligatorios = array('descripcion','codigo','codigo_bis','descripcion_select','n_boletos',
            'n_boletos_extra','n_ingresos','evento','nombre_completo','licenciatura','generacion','domicilio',
            'fecha_hora','plantel');

        parent::__construct(link: $link,tabla:  $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas);
    }

    public function alta_bd(): array|stdClass
    {
        $r_alta_bd = parent::alta_bd(); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al dar de alta invitacion', data: $r_alta_bd);
        }
        return $r_alta_bd;
    }
}